### ISSUE TITLE
HTML-encoded characters don’t appear properly

### ISSUE THREAD

**Issue by AbdelrahmanManz** [PaulAshraf/is-this-the-onion#1]
## Expected Behavior
Characters should appear normally. 

## Actual Behavior
![AB1D832B-991D-4326-BAD1-DAC28FA1B8DB](https://user-images.githubusercontent.com/24511018/82888972-54f59b80-9f4a-11ea-903b-26e48e011180.jpeg)

## Steps to Reproduce the Problem

  1.refresh until you get a question that has symbols. 

## Specifications

  - Version: 1.0 (I guess lol)
  - Platform: iOS

**Comment by PaulAshraf** [comment]
**Fixed** by using `underscore` package to parse the HTML characters.

Thanks for the feedback! 👍
